In [ ]:
import pandas as pd
import numpy as np
# Creating a Series
s = pd.Series([10, 20, 30])
print(s)

0    10
1    20
2    30
dtype: int64


In [ ]:
d = pd.Series([30, 30, 40, 50, 60], index = ['a', 'b', 'c', 'd', 'e'])
d

a    30
b    30
c    40
d    50
e    60
dtype: int64

In [ ]:
#Create a data frame
data = {
    'Person': ['Joe', 'Eric', 'Mary'],
    'Subject': ['Maths', 'English', 'Hindi']
}
df = pd.DataFrame(data)
df

Person  Subject
0    Joe    Maths
1   Eric  English
2   Mary    Hindi

##Reading and Writing Files

In [ ]:
df = pd.read_csv('person20.csv')
print(df)


       Name  Age           City
0     Alice   25       New York
1       Bob   30         London
2   Charlie   35          Paris
3     David   28         Berlin
4      Emma   22        Toronto
5     Frank   33         Sydney
6     Grace   27          Tokyo
7     Henry   31  San Francisco
8       Ivy   24        Chicago
9      Jack   29         Mumbai
10    Kathy   26          Dubai
11     Liam   32      Singapore
12      Mia   23    Los Angeles
13     Noah   34        Bangkok
14   Olivia   21      Barcelona
15     Paul   36       Istanbul
16    Quinn   27           Rome
17   Rachel   30          Seoul
18    Steve   33      Amsterdam
19     Tina   25      Melbourne


In [ ]:
df.to_excel('person_excel.xlsx')

In [ ]:
df.to_excel('person2_excel.xlsx', index=False)

In [ ]:
df = pd.read_excel('person2_excel.xlsx')
print(df)

   Unnamed: 0     Name  Age      City
0           0    Alice   25  New York
1           1      Bob   30    London
2           2  Charlie   35     Paris


In [ ]:
df.to_csv('person2_csv.csv')

In [ ]:
df.to_csv('person2_csv.csv', index=False)

##Exploring data


In [ ]:
print(df.head())

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   28    Berlin
4     Emma   22   Toronto


In [ ]:
df.tail()

Name  Age       City
15    Paul   36   Istanbul
16   Quinn   27       Rome
17  Rachel   30      Seoul
18   Steve   33  Amsterdam
19    Tina   25  Melbourne

In [ ]:
df.describe()

Age
count  20.000000
mean   28.550000
std     4.454152
min    21.000000
25%    25.000000
50%    28.500000
75%    32.250000
max    36.000000

In [ ]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [ ]:
df.shape

(20, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    20 non-null     object
 1   Age     20 non-null     int64 
 2   City    20 non-null     object
dtypes: int64(1), object(2)
memory usage: 612.0+ bytes


In [ ]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=20, step=1)

## Data Selection and Filtering


In [ ]:
df = pd.read_csv('Automobile.csv')
print(df)

                          name   mpg  cylinders  displacement  horsepower  \
0    chevrolet chevelle malibu  18.0          8         307.0       130.0   
1            buick skylark 320  15.0          8         350.0       165.0   
2           plymouth satellite  18.0          8         318.0       150.0   
3                amc rebel sst  16.0          8         304.0       150.0   
4                  ford torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
393            ford mustang gl  27.0          4         140.0        86.0   
394                  vw pickup  44.0          4          97.0        52.0   
395              dodge rampage  32.0          4         135.0        84.0   
396                ford ranger  28.0          4         120.0        79.0   
397                 chevy s-10  31.0          4         119.0        82.0   

     weight  acceleration  model_year  origin  
0      3504          12.0  

In [ ]:
df.to_csv('Automobile_csv.csv')

In [ ]:
df.to_excel('Automobile_excel.xlsx')

In [ ]:
df.columns

Index(['name', 'mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin'],
      dtype='object')

In [ ]:
df.info

<bound method DataFrame.info of                           name   mpg  cylinders  displacement  horsepower  \
0    chevrolet chevelle malibu  18.0          8         307.0       130.0   
1            buick skylark 320  15.0          8         350.0       165.0   
2           plymouth satellite  18.0          8         318.0       150.0   
3                amc rebel sst  16.0          8         304.0       150.0   
4                  ford torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
393            ford mustang gl  27.0          4         140.0        86.0   
394                  vw pickup  44.0          4          97.0        52.0   
395              dodge rampage  32.0          4         135.0        84.0   
396                ford ranger  28.0          4         120.0        79.0   
397                 chevy s-10  31.0          4         119.0        82.0   

     weight  acceleration  model_year  origin  
0      3504          12.0          70     usa  
1      3693          11.5          70     usa  
2      3436          11.0          70     usa  
3      3433          12.0          70     usa  
4      3449          10.5          70     usa  
..      ...           ...         ...     ...  
393    2790          15.6          82     usa  
394    2130          24.6          82  europe  
395    2295          11.6          82     usa  
396    2625          18.6          82     usa  
397    2720          19.4          82     usa  

[398 rows x 9 columns]>

In [ ]:
df.index

RangeIndex(start=0, stop=398, step=1)

In [ ]:
df.tail()


name   mpg  cylinders  displacement  horsepower  weight  \
393  ford mustang gl  27.0          4         140.0        86.0    2790   
394        vw pickup  44.0          4          97.0        52.0    2130   
395    dodge rampage  32.0          4         135.0        84.0    2295   
396      ford ranger  28.0          4         120.0        79.0    2625   
397       chevy s-10  31.0          4         119.0        82.0    2720   

     acceleration  model_year  origin  
393          15.6          82     usa  
394          24.6          82  europe  
395          11.6          82     usa  
396          18.6          82     usa  
397          19.4          82     usa

## Data Slection & Filtering

In [ ]:
# DataFrame
data = {'Name': ['Alice', 'Bob', 'Joe', 'Frank', 'Ben'], 'Age': [25, 30, 35, 40, 45], 'index':['a','b','c','d', 'e']}
df = pd.DataFrame(data)
print(df)

    Name  Age index
0  Alice   25     a
1    Bob   30     b
2    Joe   35     c
3  Frank   40     d
4    Ben   45     e


In [ ]:
df['Age']

0    25
1    30
2    35
3    40
4    45
Name: Age, dtype: int64

In [ ]:
df[['Name', 'Age']]

Name  Age
0  Alice   25
1    Bob   30
2    Joe   35
3  Frank   40
4    Ben   45

In [ ]:
df[ df['Age'] > 25 ]

Name  Age
1    Bob   30
2    Joe   35
3  Frank   40
4    Ben   45

In [ ]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [ ]:
df.loc[4]

Name    Ben
Age      45
Name: 4, dtype: object

In [ ]:
df.iloc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Joe', 'Frank', 'Ben'],
    'Age': [25, 30, 35, 40, 45]
}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
print(df)

    Name  Age
a  Alice   25
b    Bob   30
c    Joe   35
d  Frank   40
e    Ben   45


In [ ]:
df.loc['c']

Name    Joe
Age      35
Name: c, dtype: object

In [ ]:
df.loc['b': 'd']


Name  Age
b    Bob   30
c    Joe   35
d  Frank   40

In [ ]:
df.loc['c', 'Age']

np.int64(35)

In [ ]:
df.iloc[2]

Name    Joe
Age      35
Name: c, dtype: object

In [ ]:
df.iloc[0:3]

Name  Age
a  Alice   25
b    Bob   30
c    Joe   35

In [ ]:
df.iloc[2,0]

'Joe'

## Modifying Data

In [ ]:
df['NewColumn'] = df['Age'] * 2          # Create new column
df

Name  Age  NewColumn
a  Alice   25         50
b    Bob   30         60
c    Joe   35         70
d  Frank   40         80
e    Ben   45         90

In [ ]:
df['DoubleAge'] = df['Age'] * 2          # Create new column
df

Name  Age  NewColumn  DoubleAge
a  Alice   25         50         50
b    Bob   30         60         60
c    Joe   35         70         70
d  Frank   40         80         80
e    Ben   45         90         90

In [ ]:
df.rename(columns={'NewColumn': 'DoubleAge'}, inplace=True)
df

Name  Age  DoubleAge  DoubleAge
a  Alice   25         50         50
b    Bob   30         60         60
c    Joe   35         70         70
d  Frank   40         80         80
e    Ben   45         90         90

In [ ]:
df.drop('DoubleAge', axis=1, inplace=True)  #Drop Column
df

Name  Age
a  Alice   25
b    Bob   30
c    Joe   35
d  Frank   40
e    Ben   45

In [ ]:
df.drop(0, axis=0, inplace=True)      # Drop row
df

##Handling Missing Data

In [ ]:
#1. Handling Missing Data
#Imputation
import pandas as pd
import numpy as np

# Sample dataset similar to your image
data = {
    'Name': ['John', 'Alice', 'Bob', 'Sara'],
    'Math Score': [85, 90, '', 88]
}
df = pd.DataFrame(data)
df

Name Math Score
0   John         85
1  Alice         90
2    Bob           
3   Sara         88

In [ ]:
# Replace 'Missing' with np.nan
df['Math Score'] = df['Math Score'].replace('', np.nan)
df

/tmp/ipython-input-1662096404.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Math Score'] = df['Math Score'].replace('', np.nan)


Name  Math Score
0   John        85.0
1  Alice        90.0
2    Bob         NaN
3   Sara        88.0

In [ ]:
df['Math Score'] = pd.to_numeric(df['Math Score']) #Convert datatype

df.dtypes

Name           object
Math Score    float64
dtype: object

In [ ]:
# Impute missing value with mean
mean_value = df['Math Score'].mean()
df['Math Score'].fillna(mean_value, inplace=True)
df

/tmp/ipython-input-49-2380196942.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Math Score'].fillna(mean_value, inplace=True)


Name  Math Score
0   John   85.000000
1  Alice   90.000000
2    Bob   87.666667
3   Sara   88.000000

## Delete Missing Data

In [ ]:
# Convert to numeric (optional)
import pandas as pd

# Create a sample DataFrame with missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', None],
    'Age': [25, None, 30, 22],
    'City': ['New York', 'Los Angeles', None, 'Chicago']
}

df = pd.DataFrame(data)
df

Name   Age         City
0    Alice  25.0     New York
1      Bob   NaN  Los Angeles
2  Charlie  30.0         None
3     None  22.0      Chicago

In [ ]:
# Drop rows with any missing values
df_cleaned = df.dropna()

print("\nDataFrame after dropping rows with missing data:")
print(df_cleaned)


DataFrame after dropping rows with missing data:
    Name   Age      City
0  Alice  25.0  New York


##Remove Duplicates

In [ ]:
# Sample data with duplicates
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 22],
    'City': ['New York', 'Chicago', 'New York', 'Houston']
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

NameError: name 'pd' is not defined

In [ ]:
df_corrected = df.drop_duplicates() # Remove duplicate rows

print("\nDataFrame after dropping rows with missing data:")
print(df_corrected)


DataFrame after dropping rows with missing data:
    Name  Age      City
0  Alice   25  New York
1    Bob   30   Chicago
3  David   22   Houston


## Assignment


In [ ]:


data = {
    'StudentID': [101, 102, 103, 104, 105, 106, 106],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Frank'],
    'Subject': ['Math', 'Math', 'Science', 'Science', 'Math', 'Science', 'Science'],
    'Marks': [88, 76, 90, 65, 88, 70, 70],
    'Grade': ['A', 'B', 'A', 'C', 'A', 'B', 'B']
}

df = pd.DataFrame(data)
print(df)

   StudentID     Name  Subject  Marks Grade
0        101    Alice     Math     88     A
1        102      Bob     Math     76     B
2        103  Charlie  Science     90     A
3        104    David  Science     65     C
4        105      Eva     Math     88     A
5        106    Frank  Science     70     B
6        106    Frank  Science     70     B


## Datatypes & Conversion (Saturday)


In [ ]:
import pandas as pd

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': ['25', '30', '35', '40'],          # Strings, not numbers
    'JoiningDate': ['2023-01-01', '2022-12-15', '2023-03-10', '2023-06-01'],
    'Salary': [50000.0, 60000.0, None, 70000.0],  # Float with missing
    'IsPermanent': ['True', 'False', 'True', 'True']  # Strings, not bool
}
df = pd.DataFrame(data)
print(df)

      Name Age JoiningDate   Salary IsPermanent
0    Alice  25  2023-01-01  50000.0        True
1      Bob  30  2022-12-15  60000.0       False
2  Charlie  35  2023-03-10      NaN        True
3    David  40  2023-06-01  70000.0        True


In [ ]:
#Convert age datatype to int
df['Age'] = df['Age'].astype(int)
df.dtypes

Name            object
Age              int64
JoiningDate     object
Salary         float64
IsPermanent     object
dtype: object

In [ ]:
df['JoiningDate'] = pd.to_datetime(df['JoiningDate'])
df.dtypes

Name                   object
Age                     int64
JoiningDate    datetime64[ns]
Salary                float64
IsPermanent            object
dtype: object

In [ ]:
#Convert ispermanant to boolean
df['IsPermanent'] = df['IsPermanent'].str.strip().str.lower()
df['IsPermanent'] = df['IsPermanent'].map({'true': True, 'false': False})

print(df)

      Name Age JoiningDate   Salary  IsPermanent
0    Alice  25  2023-01-01  50000.0         True
1      Bob  30  2022-12-15  60000.0        False
2  Charlie  35  2023-03-10      NaN         True
3    David  40  2023-06-01  70000.0         True


In [ ]:
print(df['IsPermanent'].unique())

['True' 'False']


In [ ]:
df['IsPermanent'] = df['IsPermanent'].str.strip().str.lower()
df['IsPermanent'] = df['IsPermanent'].astype(bool)
df.dtypes
df

Name Age JoiningDate   Salary  IsPermanent
0    Alice  25  2023-01-01  50000.0         True
1      Bob  30  2022-12-15  60000.0         True
2  Charlie  35  2023-03-10      NaN         True
3    David  40  2023-06-01  70000.0         True

## Maths & Stats in Pandas

In [ ]:
import pandas as pd

data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Math': [90, 80, 85, 70, 95],
    'Science': [88, 92, 80, 75, 85],
    'English': [78, 85, 88, 90, 82]
}

df = pd.DataFrame(data)
print(df)

   Student  Math  Science  English
0    Alice    90       88       78
1      Bob    80       92       85
2  Charlie    85       80       88
3    David    70       75       90
4      Eva    95       85       82


In [ ]:
df.describe()

Math    Science    English
count   5.000000   5.000000   5.000000
mean   84.000000  84.000000  84.600000
std     9.617692   6.670832   4.774935
min    70.000000  75.000000  78.000000
25%    80.000000  80.000000  82.000000
50%    85.000000  85.000000  85.000000
75%    90.000000  88.000000  88.000000
max    95.000000  92.000000  90.000000

In [ ]:
#Stats against columns

print(df['Math'].min())
print(df['Math'].sum())
print(df['Math'].mean())
print(df['Math'].max())

70
420
84.0
95


In [ ]:
#Column-Wise/ Row-wise Aggregation.

df.mean(numeric_only=True) # Mean marks in each subject

Math       84.0
Science    84.0
English    84.6
dtype: float64

In [ ]:
# Total marks for each student (For row-wise axis =1)
df['Total'] = df[['Math', 'Science', 'English']].sum(axis=1)
print(df)

   Student  Math  Science  English  Total
0    Alice    90       88       78    256
1      Bob    80       92       85    257
2  Charlie    85       80       88    253
3    David    70       75       90    235
4      Eva    95       85       82    262


In [ ]:
# Average marks per student
df['Average'] = df[['Math', 'Science', 'English']].mean(axis=1)
print(df)

   Student  Math  Science  English  Total    Average
0    Alice    90       88       78    256  85.333333
1      Bob    80       92       85    257  85.666667
2  Charlie    85       80       88    253  84.333333
3    David    70       75       90    235  78.333333
4      Eva    95       85       82    262  87.333333


In [ ]:
#Custom Aggregation
df[['Math', 'Science']].agg(['min', 'max', 'mean', 'std'])

Math    Science
min   70.000000  75.000000
max   95.000000  92.000000
mean  84.000000  84.000000
std    9.617692   6.670832

## Day 5 - Tuesday
Outliner Detection & Treatment

Outlier Detection: Process of identifying diff cat of data from majority of data.

Methods:
Standard deviation
IQR (InterQuartile Range)
Z-Score
Clustering
Isolation Forest

Choice of detection technique depends on data statistics.


In [ ]:
import pandas as pd
import numpy as np
from scipy import stats

#Original Salary dataset
Salary = np.array([40000, 42000, 41500, 39800, 400000])

#The z-score is used to detect outliers like 400000
#We need to find the max of non-outliers salaries, here assumed to be 42000
#Replace the outlier with the max value
#Calculate z-score

z_scores = stats.zscore(Salary)
print(z_scores)

#Define a lower threshold to catch outliers in small datasets.
threshold = 1.0

#Identify outlier indices
outlier_indices = np.where(np.abs(z_scores)>threshold)[0]
print("outlier_indices ",outlier_indices)

#Get max outlier salary
non_outliers = Salary[np.abs(z_scores)<=threshold]
max_non_outlier = non_outliers.max()

#Replace outliers with Max Non-Outlier value
salary_cleaned = Salary.copy()
salary_cleaned[outlier_indices] = max_non_outlier
print("Cleaned Salaries: ", salary_cleaned)


[-0.50573359 -0.49181304 -0.49529317 -0.50712564  1.99996543]
outlier_indices  [4]
Cleaned Salaries:  [40000 42000 41500 39800 42000]


The Z-score method identifies outliers based on the number of standard deviations a data point is from the mean. A Z-score is calculated as:

z =  (DataPoints - Mean)  Standard Deviation
where:

X is the data point,
μ is the mean, and
σ is the standard deviation.

Pros and Cons

Pros: Easy to implement, works well for normally distributed data.
Cons: Not ideal for skewed data, sensitive to extreme outliers.

In [ ]:
import numpy as np
import pandas as pd

# Sample data
data = {'values': [12, 15, 14, 10, 102, 13, 11, 14, 13, 15, 110]}
df = pd.DataFrame(data)
# Calculate Z-scores
df['z_score'] = (df['values'] - df['values'].mean()) / df['values'].std()
# Identify outliers
outliers = df[np.abs(df['z_score']) > 1.6]
print("Outliers:\n", outliers)

Outliers:
     values   z_score
4      102  1.912494
10     110  2.124726


In [ ]:
#Replace outliers with Max Non-Outlier value
median_value = df['values'].median()
df.loc[np.abs(df['z_score']) > threshold, 'values'] = median_value

# Drop z_score column after treatment
df.drop('z_score', axis=1, inplace=True)

print("\nAfter Treatment:\n", df)



After Treatment:
     values
0       12
1       15
2       14
3       10
4       14
5       13
6       11
7       14
8       13
9       15
10      14


##Day 6 - Correcting Data

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'State': ['Califronia', 'NY', 'new york'],
    'Age': [25, 30, 35]
}
df = pd.DataFrame(data)
df

Name       State  Age
0    Alice  Califronia   25
1      Bob          NY   30
2  Charlie    new york   35

In [ ]:
#Dictionary of incorrect to correct values
corrections = {
    'Califronia': 'California',
    'NY': 'New York',
    'new york': 'New York'
}

#Apply corrections
df['State'] = df['State'].replace(corrections)
df

Name       State  Age
0    Alice  California   25
1      Bob    New York   30
2  Charlie    New York   35

In [ ]:
# Sample data with inconsistent formats
data = {
    'Name': ['alice', 'BOB', 'Charlie'],
    'Date of Birth': ['01/02/1990', '1990-02-01', 'Feb 1, 1990'],
    'Phone Number': ['(123) 456-7890', '123.456.7890', '+1-123-456-7890']
}
df = pd.DataFrame(data)
df

Name Date of Birth     Phone Number
0    alice    01/02/1990   (123) 456-7890
1      BOB    1990-02-01     123.456.7890
2  Charlie   Feb 1, 1990  +1-123-456-7890

In [ ]:
df['Name'] = df['Name'].str.title()
df

Name Date of Birth     Phone Number
0    Alice    01/02/1990   (123) 456-7890
1      Bob    1990-02-01     123.456.7890
2  Charlie   Feb 1, 1990  +1-123-456-7890

In [ ]:
#Standardize Date to yyyy-mm-dd format
df['Date of Birth'] = pd.to_datetime(df['Date of Birth'],format = 'mixed').dt.strftime('%Y-%m-%d')
df


Name Date of Birth     Phone Number
0    Alice    1990-01-02   (123) 456-7890
1      Bob    1990-02-01     123.456.7890
2  Charlie    1990-02-01  +1-123-456-7890

In [ ]:
#Apply Format to Phone Number
import re
df['Phone Number'] = df['Phone Number'].apply(lambda x: re.sub(r'\D', '', x))  # Remove non-digit characters

print("Standardized DataFrame:")
print(df)

Standardized DataFrame:
      Name Date of Birth Phone Number
0    Alice    1990-01-02   1234567890
1      Bob    1990-02-01   1234567890
2  Charlie    1990-02-01  11234567890


In [ ]:
#Normalization: Is a process of scaling numeric values to a common range ussually between 0 & 1.
#Min-Max Normalization

'''X(norm) = X-x(min)/(x(max)-x(min))

where:
X min is the minimum value of feature
X max is the maximum value of feature '''

#Normalize Data below (Min-Max Normalization):

import numpy as np
# Original exam scores
scores = np.array([60, 75, 88, 92, 55, 70])

# Min-Max normalization
normalized_scores = (scores - scores.min()) / (scores.max() - scores.min())
'''min-max normalization:
scores.min() → 55
scores.max() → 92
So the range is 92 - 55 = 37'''

#For 60 → (60−55)/37=0.1351
#For 75 → (75−55)/37=0.5405. Use this for rest of scores.

print("Original Scores:", scores)
print("Normalized Scores:", normalized_scores)


Original Scores: [60 75 88 92 55 70]
Normalized Scores: [0.13513514 0.54054054 0.89189189 1.         0.         0.40540541]


In [ ]:
# One-Hot Encoding

import pandas as pd
#one hot encoding
# Sample data
data = {
    'Item': ['Ball', 'Car', 'Doll'],
    'Color': ['Red', 'Blue', 'Green']
}

df = pd.DataFrame(data)

#Apply one-hot encoding to the Color column
encoded = pd.get_dummies(df,columns=['Color'],dtype=int)
encoded

Item  Color_Blue  Color_Green  Color_Red
0  Ball           0            0          1
1   Car           1            0          0
2  Doll           0            1          0

##Numpy (Numerical Python)

In [ ]:
# Used for fast numerical competitions, handling arrays, matrixes and high performance operations.
import numpy as np

#Array Creation
# 1D array
a = np.array([1, 2, 3])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3]
1
(3,)


In [ ]:
# 2D array
b = np.array([[1, 2], [3, 4]])
print(b)
print(b.ndim)
print(b.shape)


[[1 2]
 [3 4]]
2
(2, 2)


In [ ]:
c = np.array([[1, 2], [3, 4], [5, 6]]) # 2 Dim
print(c)
print(c.ndim)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [ ]:
a3 = np.array([
    [[1, 2], [3, 4],[11, 12]],
    [[5, 6], [7, 8], [13,14]]
])
print("3D:", a3.ndim)
print(a3)
print(a3.shape)

3D: 3
[[[ 1  2]
  [ 3  4]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]]]
(2, 3, 2)


In [ ]:
a4 = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ]
])
print("4D:", a4.ndim)
print(a4)
print(a4.shape)

4D: 4
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
(1, 2, 2, 2)


In [ ]:
a5 = np.array([
    [
        [
            [[1, 2], [3, 4]],
            [[5, 6], [7, 8]]
        ]
    ]
])
print("5D:", a5.ndim)
print(a5)
print(a5.shape)

5D: 5
[[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]]
(1, 1, 2, 2, 2)


In [ ]:
#Array of Zeros
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Array of Ones
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#Range of Numbers
array1 = np.arange(0,10,2) #syntax=start, stop, step(increment)
array1

array([0, 2, 4, 6, 8])

In [ ]:
array_odd = np.arange (1,10,2)
array_odd

array([1, 3, 5, 7, 9])

In [ ]:
desc_numbers = np.arange(10,0,-1)
print(desc_numbers)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
floats = np.arange(0, 1, 0.2)
print("Float steps:", floats)

Float steps: [0.  0.2 0.4 0.6 0.8]


In [ ]:
# Evenly spaced values (like linspace) .....lin divides the numbers evenly
lin = np.linspace(0, 1, 5) #start, stop, # of division
print(lin)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Identity matrix ...... 1 is always in diagonal position
eye = np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
eye = np.eye(3,4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
eye = np.eye(3,3,k=1) #shift diagonal upward
print(eye)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
eye = np.eye(3,3,k=-1) #shift diagonal downward
print(eye)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
eye = np.eye(3, dtype=int)
print(eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
a = np.array([1, 2, 3], dtype='float64') #Specifying datatype at array creation
print(a)
print(a.dtype)

[1. 2. 3.]
float64


##Array Indexing and Slicing

In [ ]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[1:4])
print(a[1:4:2])

10
50
[20 30 40]
[20 40]


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[1, 2]) # Prints array locations
print(b[0,2])
print(b[1:3])
print(b[1:2])
print(b[1:1])
print(b[:1]) #prints array with 0 index. 1 is excluded
print(b[:,1])#prints element 1 of all arrays
print(b[:,2])#prints element 2 of all arrays
print(b[0,1:3])#prints element 2 and 3 of 0 index array

6
3
[[4 5 6]]
[[4 5 6]]
[]
[[1 2 3]]
[2 5]
[3 6]
[2 3]


##Data Types and Type Conversions

In [ ]:
a = np.array([1, 2, 3])
print(a.dtype)


int64


In [ ]:
# Convert to float
a = a.astype(float)
print(a.dtype)

float64


In [ ]:
#Float to Int
f = np.array([3.7, 1.2, 9.8])
i = f.astype(int)
print(i)

[3 1 9]


In [ ]:
s = np.array(['1', '2', '3'])
n = s.astype(int)
print(n)


[1 2 3]


In [ ]:
s = np.array(['1', 'two', '3']) #Error
n = s.astype(int)

ValueError: invalid literal for int() with base 10: np.str_('two')

In [ ]:
#To Boolean
a = np.array([0, 1, 2, 0, 5])
print(a.astype(bool))

[False  True  True False  True]


In [ ]:
#string to float
s = np.array(['4.5', '5.7', '8.9'])
f = s.astype(float)
print(f)

[4.5 5.7 8.9]


##Array Operations

In [ ]:
#Arithmetic Operations
a = np.array([1,3,4])
b = np.array([4,5,6])

print(a+b)
print(a*b)
print(a**2) #a exponent 2
print(a/b)
print(a-b)
print(a+10)

[ 5  8 10]
[ 4 15 24]
[ 1  9 16]
[0.25       0.6        0.66666667]
[-3 -2 -2]
[11 13 14]


In [ ]:
#Aggregate Functions

c = np.array([3,5,6,7,8])
print(c.sum())
print(c.mean())
print(c.max())
print(c.min())
print(c.std())
print(c.cumsum())

29
5.8
8
3
1.7204650534085253
[ 3  8 14 21 29]


In [ ]:
#Logical and Comparison Operations
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(a == b)
print(a > b)
print(a < b)


[False  True False]
[False False  True]
[ True False False]
[False  True False]


In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([15, 20, 25, 40])

# Logical AND
print(np.logical_and(a == 20, b == 20))

# Logical OR
print(np.logical_or(a < 20, b > 30))

# Logical NOT
print(np.logical_not(a > 25))

[False  True False False]
[ True False False  True]
[ True  True False False]


##Array reshaping and transposing

In [ ]:
a = np.arange(6)
print(a)
print(a.shape)

b = a.reshape(2,3)
print(b)
print(b.shape)
print(b.T)
print(b.shape)

[0 1 2 3 4 5]
(6,)
[[0 1 2]
 [3 4 5]]
(2, 3)
[[0 3]
 [1 4]
 [2 5]]
(2, 3)


In [ ]:
#Stacking Arrays (Vertical and Hoerizontal Stacking)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.array([[7], [9]])
print(np.vstack([a, b]))   # Stack vertically (row-wise)
print(np.hstack([a, c]))   # Stack horizontally (column-wise)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 9]]


In [ ]:
#Deletion and Insertion
a = np.array([1, 2, 3, 4])
a_del = np.delete(a, 2)       # Deletes index 2 (value 3)
print(a_del)

a_ins = np.insert(a, 2, 99)   # Inserts 99 at index 2
print(a_ins)

[1 2 4]
[ 1  2 99  3  4]


In [ ]:
# Where conditions
a = np.array([10, 15, 20, 25])

# Conditionally select
print(np.where(a > 15, "High", "Low"))

['Low' 'Low' 'High' 'High']


In [ ]:
np.random.seed(42)

print(np.random.rand(2, 2))       # Random floats [0,1)
print(np.random.randint(1, 100, 5))  # 5 random ints [1,100)

# Shuffle
a = np.array([1, 2, 3, 4])
np.random.shuffle(a)
print(a)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
[83 87 75 75 88]
[4 2 3 1]


In [ ]:
# Returning Indexes
import numpy as np

arr = np.array([10, 15, 20, 25, 30])
idx = np.where(arr > 20)
print(idx)
print(arr[idx])

(array([3, 4]),)
[25 30]


In [ ]:
#Replacing Values
arr = np.array([10, 15, 20, 25, 30])
arr[arr > 20] = 0
print(arr)



[10 15 20  0  0]


In [ ]:
arr = np.array([10, 15, 20, 25, 30])
new_arr = np.where(arr > 20, 999, arr) #if condition is true, replace or maintain
print(new_arr)

[ 10  15  20 999 999]


In [ ]:
# Return Index of Min and Max Value
arr = np.array([10, 20, 5, 30, 25])

min_index = np.argmin(arr)
max_index = np.argmax(arr)

print("Min index:", min_index)
print("Max index:", max_index)

Min index: 2
Max index: 3


In [ ]:
#Return Indexes of non-zerp elements
arr = np.array([0, 1, 0, 2, 3])
print(np.nonzero(arr))

(array([1, 3, 4]),)


In [ ]:
#Boolean Indexes
arr = np.array([10, 15, 20, 25, 30])
mask = arr > 20
print(arr[mask])

[25 30]


In [ ]:
#Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])
indexes = [1, 3, 4]
print(arr[indexes])

[20 40 50]


In [ ]:
#np.Take & np.Put Functions
arr = np.array([10, 20, 30, 40])
print(np.take(arr, [0, 2]))

np.put(arr, [0, 2], [111, 999])
print(arr)

[10 30]
[111  20 999  40]


In [ ]:
#Returns element that satisfies the condition
arr = np.array([10, 20, 30, 40, 50])
condition = arr > 25
print(np.extract(condition, arr))

[30 40 50]


##Saving and Loading Arrays

In [ ]:
a = np.array([1, 2, 3, 4])

# Save to file
np.save('my_array1.npy', a)

# Load from file
loaded = np.load('my_array1.npy')
print(loaded)

[1 2 3 4]


##Handling Missing Values

In [ ]:
import numpy as np

#Checking missing values
arr = np.array([1, 2, np.nan, 4, 5])
print(np.isnan(arr))

#Counting missing values
print(np.sum(np.isnan(arr)))

#Replacing missing values with 0
arr[np.isnan(arr)] = 0
print(arr)


[False False  True False False]
1
[1. 2. 0. 4. 5.]


In [ ]:
#Replacing missing values with mean
arr = np.array([1, 2, np.nan, 4, 5])
mean_val = np.nanmean(arr)
arr[np.isnan(arr)] = mean_val
print(arr)  # [1. 2. 3. 4. 5.]

[1. 2. 3. 4. 5.]
