# **3. Newswire Classification using ANN**

In [8]:
import pandas as pd
import numpy as np

from tensorflow.keras.datasets import reuters
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense


# --- a) Load the Reuters dataset ---
max_words = 10000
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=max_words)

# --- b) Apply padding ---
# Setting length to 200 as per model requirements
maxlen = 200
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test = pad_sequences(x_test, maxlen=maxlen)

# --- c) One-hot encode the target labels ---
# Reuters dataset contains 46 possible categories
y_train = to_categorical(y_train, 46)
y_test = to_categorical(y_test, 46)

# Print confirmation
print(f"Dataset loaded using keras.datasets.reuters")
print(f"X_train shape: {x_train.shape} (Padded to 200)")
print(f"Y_train shape: {y_train.shape} (One-hot encoded for 46 classes)")

Dataset loaded using keras.datasets.reuters
X_train shape: (8982, 200) (Padded to 200)
Y_train shape: (8982, 46) (One-hot encoded for 46 classes)


In [9]:
# d) Build the Sequential model
model = Sequential()

# Embedding layer: vocab size 10k, vector dim 128, input length 200
model.add(Embedding(input_dim=10000, output_dim=128, input_length=200))

# LSTM layer with 64 units
model.add(LSTM(64))

# Output layer with 46 units and Softmax activation
model.add(Dense(46, activation='softmax'))

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:

# train the model
history = model.fit(x_train, y_train,
                    epochs=10,            # It needs several rounds to learn
                    batch_size=32,
                    validation_split=0.2) # Saves 20% to check progress

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

print("Model compiled successfully!")



Epoch 1/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 31s 127ms/step - accuracy: 0.4335 - loss: 2.3004 - val_accuracy: 0.4830 - val_loss: 1.9664
Epoch 2/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 29s 127ms/step - accuracy: 0.5365 - loss: 1.7920 - val_accuracy: 0.5771 - val_loss: 1.6849
Epoch 3/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 28s 126ms/step - accuracy: 0.5880 - loss: 1.5856 - val_accuracy: 0.6138 - val_loss: 1.5302
Epoch 4/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 30s 133ms/step - accuracy: 0.6612 - loss: 1.3087 - val_accuracy: 0.6411 - val_loss: 1.4341
Epoch 5/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 41s 134ms/step - accuracy: 0.7157 - loss: 1.1199 - val_accuracy: 0.6694 - val_loss: 1.3689
Epoch 6/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 41s 133ms/step - accuracy: 0.7665 - loss: 0.9270 - val_accuracy: 0.6800 - val_loss: 1.3553
Epoch 7/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 28s 126ms/step - accuracy: 0.8085 - loss: 0.7688 - val_accuracy: 0.6934 - val_loss: 1.3755
Epoch 8/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 29s 131ms/step - accuracy: 0.8419 - loss: 0

In [14]:
# Evaluate on test data
results = model.evaluate(x_test, y_test)

print(f"\nTest Loss: {results[0]:.4f}")
print(f"Test Accuracy: {results[1]:.4f}")


71/71 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - accuracy: 0.6616 - loss: 1.6116

Test Loss: 1.6116
Test Accuracy: 0.6616


**4. Scikit-learn for a Classification Task**









In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Load the Iris dataset
iris = load_iris()
X = iris.data  # Features: sepal length, sepal width, etc.
y = iris.target # Labels: setosa, versicolor, virginica

# 2. Split into Training (80%) and Testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize and train a Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# 4. Make predictions on the test data
y_pred = clf.predict(X_test)



In [16]:
# Evaluate Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy:.2f}")

# Generate Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

# Classification Report (Precision, Recall, F1)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))


Accuracy Score: 1.00

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

